### ISSUE TITLE
Hotel Dusk: Room 215 Pixellated lines on top of animated screens

### ISSUE THREAD

**Issue by klunkee** [ahezard/nds-bootstrap#260] opened 2018-06-28 06:05 UTC
There are large blocky moving lines across the top of both screens which appear on any scene with any kind of animation or video. The game is played with the DS held sideways vertically like a book so the lines appear on the left (or what would be the top when the DS is held horizontally). 

It's kind of an interesting glitch, the lines first appear in the first video and are very large and green and later seem to be dark grey. Otherwise the game seems to run totally fine and static scenes and screens don't show the lines.

**Comment by Stack3r** [comment] 2018-06-28 18:16
@klunkee Do you mind adding a picture of the issue here?

**Comment by hubert-skowronek** [comment] 2018-06-29 12:58
@Stack3r [https://i.imgur.com/GomjGMa.jpg](https://i.imgur.com/GomjGMa.jpg)

**Comment by damianoamatruda** [comment] 2018-08-14 21:34
Duplicate of #231

**Closed by damianoamatruda** 2018-08-14 21:34 UTC
Labels: Bug, Retail
