### ISSUE TITLE
TETRIS DS Black Screen after finishing Marathon mode

### ISSUE THREAD

**Issue by Fusle** [ahezard/nds-bootstrap#296] opened 2018-07-07 10:35 UTC
Platform: N3DS running Luma3DS v9.0-e5948ab7
Load Method: DSi Menu ++
DSi Menu ++ version: v5.0.0
ROM Number: 0366
TID: ATRE
ROM Name: TETRIS DS
Region: USA
nds-bootstrap version: v0.10.1
ARM9 CPU Speed: 133mhz (TWL)
Sound/Mic frequency: 47.61 kHz

ROM gets stuck in a black screen after showing the credits when finishing Marathon mode. I've been able to replicate this multiple times

**Comment by Megahaosguy** [comment] 2018-07-07 21:03
Have you tried completing marathon mode with 67mhz? I've completed marathon mode on both my DSi and o3DS and returned to the title screen with no issues.

**Comment by Fusle** [comment] 2018-07-07 23:07
I just tried your suggestion but unfortunately I came to the same end. Are there, by any chance, other things I could try?

**Comment by Antonio231102** [comment] 2018-11-01 04:44
Unfortunately as of now this issue is still present. Hopefully it can be solved in the near future.

**Comment by ahezard** [comment] 2019-03-03 20:21
This is caused by #259

**Comment by NightYoshi370** [comment] 2019-03-17 22:57
Closing as it's not related to Tetris itself and rather the Soft-Reset issue

**Closed by NightYoshi370** 2019-03-17 22:57 UTC
Labels: Enhancement, Needs Testing, Retail
