### ISSUE TITLE
Tetris

### ISSUE THREAD

**Issue by CoolStarDood** [ahezard/nds-bootstrap#542] opened 2019-02-20 17:38 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [# ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [# ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ #]  Release _[I don't know what version, but its the one that came with TWLmenu++ v7.40]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Tetris DS

### Expected behaviour

I should just go back a menu

### Actual behaviour

freeze/crash, and the only way to get out is the power button

### Steps to reproduce

1. open game
2. select wifi
3. select either wifi settings or wifi battle, then press B to go back a menu

### Other notes
Edit: forgot to mention this, but i have the wiimmfi DNS in my wifi settings (so i can play online), but i dont think thats it

**Comment by dubbz82** [comment] 2019-03-03 02:20
I believe this is related to the soft reset that happens in other games (for example NSMB's mini games)

**Comment by dubbz82** [comment] 2019-03-03 20:19
I also have a sneaking suspicion that it's related to #296 as it's the same game, and likely the same reset method....

**Comment by ahezard** [comment] 2019-03-03 20:21
This is caused by #259

**Comment by CoolStarDood** [comment] 2019-03-03 20:25
> This is caused by #259

Oh ok

**Comment by NightYoshi370** [comment] 2019-03-17 22:57
Closing as it's not related to Tetris itself and rather the Soft-Reset issue

**Closed by NightYoshi370** 2019-03-17 22:57 UTC
Labels: Enhancement, Retail
