### ISSUE TITLE
Saving in WarioWare DIY doesn't work properly

### ISSUE THREAD

**Issue by SpankyPants1** [ahezard/nds-bootstrap#702] opened 2019-07-14 22:15 UTC
Hey, so I was playing WarioWare DIY using the newest version of nds-bootstrap, and I noticed that while the game tracks my progress, it doesn't actually save any of the games I have made. I am playing on a DSi with both HiyaCFW and Twilight-Menu++ installed, and I am using the release version of nds-bootstrap. I know that nds-bootstrap used to have a problem where it would not save the game at all, and IIRC, this was because the game saved differently from 99% of the DS library. Could this bug be a result of the game's weird save system, or is it not working because of my sheer incompetence?

**Comment by RocketRobz** [comment] 2019-07-14 22:19
You did nothing wrong.
It's currently normal for it to not save the games you made yet.

Also, this issue is duplicate of #675

**Closed by RocketRobz** 2019-07-14 22:19 UTC
