### ISSUE TITLE
WarioWare d.i.y Saving Problem

### ISSUE THREAD

**Issue by SansUndertaleXd** [ahezard/nds-bootstrap#855] opened 2020-01-31 02:48 UTC
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[latest]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

WarioWare d.i.y

### Expected behaviour

The game should save all things I create

### Actual behaviour

The game progresses fine, but the problem is that everytime I ship a microgame/record the game says that it has been shipped but when I go to check it dissappears

### Steps to reproduce

1. Boot the game
2. Create something
3. Try to ship it

**Comment by dubbz82** [comment] 2020-01-31 03:16
Dupe of #675

**Closed** 2020-01-31 18:05 UTC
