### ISSUE TITLE
Compatibility list update NDS Bootstrap

### ISSUE THREAD

**Issue by BlackRider59** [ahezard/nds-bootstrap#423] opened 2018-09-18 19:18 UTC
I think you guys need to update your compatibility list because you seem to have gotten the regions mixed up for the game Wario: Master of disguise. The EUR and USA versions give you a white screen while the JPN version works fine.

Didn't know how else to contact you so I've posted it here.

**Comment by dubbz82** [comment] 2018-09-20 13:05
Dupe of #397

**Comment by BlackRider59** [comment] 2018-09-20 14:08
No, I wasn't trying to duplicate it. I was pointing out that there is a working version, its just different to the one listed.

**Comment by BlackRider59** [comment] 2018-09-20 14:11
Oh I noticed you replied to a comment I left today in another thread. I see the confusion now. Ok i'll take this one down to avoid future misunderstandings.

**Closed** 2018-09-20 14:11 UTC
