### ISSUE TITLE
Pokemon Platinum USA Freezing

### ISSUE THREAD

**Issue by Toblerone1** [ahezard/nds-bootstrap#704] opened 2019-07-17 03:59 UTC
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x ]  Unlaunch+HiyaCFW _[please specify versions of both]_
Latest of both as of 7/10, going off of the dsi cfw guide
3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
Latest as of 7/10
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Pokemon Platinum USA
### Expected behaviour

Tell us what should happen
Not crashing and playing fine
### Actual behaviour

Tell us what happens instead
Crashes. Seems to be especially when the underground is involved, but there have been crashes outside of the underground. It freezes on a frame, no animations or anything going, and the music keeps playing. Buttons do nothing and neither does waiting. Progress is lost. 
### Steps to reproduce

1. Playing the game in general.
2. But it seems underground triggers it more often, as everytime I've spent time down there for more than a couple minutes it freezes, sometimes pretty quickly, sometimes after I've done lots of mining.
3.

### Other notes
Settings are default.

**Comment by RocketRobz** [comment] 2019-07-17 04:01
Hmm, try holding L immediately after pressing A/START to launch the game in TWLMenu++, and see if that fixes the crash.

**Comment by CaptainLibrary** [comment] 2019-08-17 23:21
Experiencing the same issue but in Diamond. Nightly and Release bootstrap. Especially bad on the Underground, but happens randomly elsewhere. Holding L at load did not fix. 
Cheers

**Comment by RocketRobz** [comment] 2019-10-23 04:14
Does the bug persist in v0.26.1?

**Comment by PurpleHazeFeedback** [comment] 2019-10-29 13:16
For me it does, don't know about others. This time the only noticeable difference is that the Poketch Digital Watch shows 00:00 instead of the real time, when everything freezes (maybe it happens when the game tries to change from morning to day, day to night or night to morning, but I'm not sure on that).

**Comment by PurpleHazeFeedback** [comment] 2019-11-01 20:34
> 
> 
> Does the bug persist in v0.26.1?

Oh, and also, it seems to freeze a whole lot in Route 217, where the heavy snowing effect is.

**Comment by RocketRobz** [comment] 2020-01-23 06:21
Can you see if the bug is fixed in the latest nightly?

**Comment by CaptainLibrary** [comment] 2020-01-23 13:43
@RocketRobz I had a crack with Diamond Version again this morning. Not Platinum but as observed above and in my own reports, I was experiencing identical issues. My setup for this test was DSi XL, Hiya CFW autobooting into TWiLightMenu++ 

Within 2 minutes I had a crash in the underground on the latest Nightly from TWLBot. NTR clock speeds. I did the digging minigame and it blackscreened (with music playing) while attempting to return to the Underground.

I rebooted and tried just running around the Underground for around 15 minutes with no crash. I didn't change any settings. Normally I would have a crash in under 5 minutes. I tried to replicate the earlier crash by doing the digging minigame a few times but it continued to play fine.

I spent another 30 minutes in my favourite crash points: the room with Marley in Victory Road, and route 217. No crashes, but crashes here are way less frequent. I'll test again after work.


**ALSO** - because it's related, I think
I'd been having a torrid time with HeartGold and SoulSilver on the latest stable bootstrap on my DSi XL - both were prone to random overworld crashes - at a much higher frequency than Diamond. NTR clock settings, with or without game enhancer cheats. I was using my own ROM dumps which work just fine with the AP patches included in TWiLight Menu ++ - I haven't extensively tried these ROMs on older versions.

I tried TWiLight Menu ++ on my 2DS XL instead and have so far had no crashes in HeartGold (3 hours of play - on the DSi I was struggling with 20 minutes). So I thought to try Diamond on my 2DS too. Still using stable release rather than nightly, I experienced none of the crashes I still get on DSi XL. I stayed in the Underground for about an hour. It was very boring but no crash :)

So then I tried a few different SD cards and MicroSD cards with adapter in the DSi XL and I had Underground crashes on Diamond once again. All the cards I use are rated for UHS. I've used 16GB and 64GB cards. I'm using the same ROM and save files and the same bootstrap / clock / vram settings as I was using on the 2DS.

**Comment by CaptainLibrary** [comment] 2020-01-23 19:06
@RocketRobz correction! Got home from work and triggered the Underground freeze in Diamond (while running around) within 10 seconds, and again in 4 minutes. DSi XL.

**Comment by RocketRobz** [comment] 2020-01-23 19:08
So I guess the crash time in the Underground is random then.

**Comment by Gemboi** [comment] 2020-01-23 19:21
All though with my full playthrough of platinum being in menus and battles is mostly safe. The main risk is idling in the overworld. But i've had most crashes in underground. The crashes usually happen in 5 minutes. Maybe the wireless connectivity exacerbates the issue. I'll run the nightly and report back

**Comment by CaptainLibrary** [comment] 2020-01-23 19:42
@RocketRobz definitely no fixed time to it, I've managed long trips down below, as well as the 10 secs freeze tonight. Above ground freezes are way less frequent and still random so hard to replicate on the new nightly. I'm'a leave it running a while to see if it happens. 

Still no freeze on 2DS XL stable bootstrap release, underground or otherwise - any possible explanation??

**Comment by RocketRobz** [comment] 2020-04-11 21:13
Duplicate of #737

**Closed by RocketRobz** 2020-04-11 21:13 UTC
Labels: Bug, Performance, Retail
