### ISSUE TITLE
Chinatown Wars - Sluggish

### ISSUE THREAD

**Issue by MarioKartFan** [ahezard/nds-bootstrap#334] opened 2018-07-25 02:16 UTC
@Robz8 Notice on the latest bootstrap (loading from SD) that Chinatown Wars runs sluggish.  I also note that if I am driving fast enough through the city, there appears to be some pop-in (terrain goes from flat purple to suddenly populated).  These issues seem to occur regardless of the clock speed.  I played this game for months on my DS, so I think these are issues with loading from SD. 

Finally more than once the game has frozen while autosaving.  When restarting, the save is corrupted.

Love NDS-Bootstrap, and all you guys have done.  Just wanted to flag these issues with Chinatown Wars.

**Comment by MarioKartFan** [comment] 2018-08-06 22:08
@ahezard @robz8 Just wanted to confirm that the Chinatown Wars performance issues remain in the latest versions of NDS-Bootstrap (including the one that @damianoamatruda posted earlier today.  I tested against the original cart today.  I would estimate that NDS-Bootstrap runs at about 2/3 of the framerate of the original.  

Thank you again for all you do.

**Comment by MarioKartFan** [comment] 2018-08-26 20:35
@ahezard @damianoamatruda @Robz8 Was excited to try out the truly excellent 11.2 with Chinatown Wars.  Unfortunately, performance remains sluggish (even with overclock and VRAM enabled).  That said, it's really impressive what you have done with so many other games.  Great work, and hope that at some point Chinatown Wars comes together!  Thanks all!

**Comment by NightYoshi370** [comment] 2018-09-16 18:16
@MarioKartFan Try the latest nightly

**Comment by ahezard** [comment] 2018-10-24 22:11
Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by RinMaru** [comment] 2018-10-24 22:59
nope it still tanks when loading in stuff

**Comment by ahezard** [comment] 2019-01-09 08:38
So this should be improved with the latest v0.14.1 release. But is performance in Chinatown Wars still an issue?

**Comment by MarioKartFan** [comment] 2019-01-09 14:08
The situation is improved but not resolved. We continue to see performance
issues. I notice far less “pop-in” than before (none in fact). But the
frame rate still hitches more than it should.

**Comment by RocketRobz** [comment] 2019-01-09 21:45
After moving cardEngine_arm9 from `0x02700000` to a cached memory region `0x023DC000`, lags are even more shorter.
Sadly, it breaks a few other games.

@ahezard Would it be possible to make `0x27000000-0x02707FFF` a cached memory region?

**Comment by RocketRobz** [comment] 2019-01-09 21:46
After moving cardEngine_arm9 from `0x02700000` to a cached memory region `0x023DC000`, lags are even more shorter.
Sadly, it breaks a few other games.

@ahezard Would it be possible to make `0x02700000-0x02707FFF` a cached memory region?

**Comment by ahezard** [comment] 2019-01-31 23:33
Could be linked to #517

**Comment by ahezard** [comment] 2019-02-26 22:26
Confirmed to be linked to dma and fixed in the branch  min_card_read_dma will be closed after the merge of this branch.

**Comment by RinMaru** [comment] 2019-02-26 23:30
is this in the latest nightly cause GTA still has minor fps drops unless that was an issue on real HW

**Comment by Stack3r** [comment] 2019-02-26 23:36
Latest nightly, care to elaborate?

**Comment by JeodC** [comment] 2019-02-26 23:39
Nightlies are based on the master branch, these commits haven't been merged yet.

**Comment by ahezard** [comment] 2019-02-26 23:39
this is not in the nightly yet

**Comment by ahezard** [comment] 2019-02-27 21:02
Should be fixed in latest nightly release please re-test

**Comment by RinMaru** [comment] 2019-02-27 22:34
its allot better but not completely gone

**Comment by MarioKartFan** [comment] 2019-03-09 01:22
@ahezard @RocketRobz 
Hi guys.  The fixes that ahezard references worked wonders, but there seems to be an issue with one of the latest nightly release.  The lag and pop-in are back again.  Maybe something was broken again?

**Comment by RocketRobz** [comment] 2019-03-09 01:26
@MarioKartFan How did you update the nightly?

**Comment by MarioKartFan** [comment] 2019-03-09 01:27
@RocketRobz 

Using your awesome TwilightMenu updater.

**Comment by RocketRobz** [comment] 2019-03-09 01:28
Check if you're still on the bootstrap nightly in TWLMenu++ settings.

**Comment by MarioKartFan** [comment] 2019-03-09 01:33
I checked already.  I'm on the nightly.

**Comment by MarioKartFan** [comment] 2019-03-09 01:34
Going to test something actually.  I wonder if when you update to the nightly TwilightMenu through your updater if that replaces the nightly bootstrap with an older version.

**Comment by MarioKartFan** [comment] 2019-03-09 01:38
No.  That wasn't the problem.  Even when updating again (and confirming that the nightly is chosen in TwilightMenu) it still hitches and has pop-in problems.

**Comment by MarioKartFan** [comment] 2019-03-09 03:04
@RocketRobz @ahezard 
Thanks for the suggestions, RocketRobz, but I checked and I am definitely on the bootstrap nightly.  I also redownloaded the latest nightly (and then checked again that it was chosen in the TWLMenu++ settings).  No dice.  It still hitches (and I'm getting pop-in again, so it's not my imagination).  I played a good 20 hours using an earlier nightly without these issues.

**Comment by RocketRobz** [comment] 2019-03-10 00:01
@MarioKartFan Can you see if the issue is fixed on the `b2b208f` commit?

**Comment by MarioKartFan** [comment] 2019-03-10 01:44
@RocketRobz I feel sort of silly saying this, but I think the answer is "not really."  The pop-in is still there, and it's still hitching.

**Comment by RocketRobz** [comment] 2019-03-10 04:28
Are you running the game with TWL or NTR clock speed?

**Comment by MarioKartFan** [comment] 2019-03-10 16:17
@RocketRobz I have tried both. Performance is degraded under either setting compared to where it was about a week ago.

**Comment by ahezard** [comment] 2019-03-10 19:36
Can you please test again with the latest nightly MarioKartFan ?

**Comment by RinMaru** [comment] 2019-03-10 19:39
looks like its good

**Comment by ahezard** [comment] 2019-03-10 19:41
Is there still some little drop RinMaru ?  
You mentionned before :
"while walking and driving the fps will drop to about 20 when areas have to load"

**Comment by RinMaru** [comment] 2019-03-10 19:44
yea there will be a small drop as the game streams in assets but its like 1/10th of a second

**Comment by ahezard** [comment] 2019-03-10 19:55
Somehow fixing this makes #538 worse
I am trying a solution that works for both

**Comment by ahezard** [comment] 2019-03-10 20:42
Can you please try again?

**Comment by MarioKartFan** [comment] 2019-03-10 21:42
Checked the latest version.  Seems you fixed the regression.  As Rin notes, there is still some hitching (it was present before the regression), but it is very slight.  The game is totally playable and far more enjoyable than it was a few weeks ago,

**Comment by MarioKartFan** [comment] 2019-03-10 21:42
Thanks a lot to you and RocketRobz.  Bootstrap is an amazing undertaking.

**Closed** 2019-03-10 21:46 UTC
Labels: Performance, Retail

**Comment by MarioKartFan** [comment] 2019-03-12 03:40
I know this is closed but after testing the latest nightly for 30 minutes it seems like performance has actually IMPROVED (beyond where it was yesterday). Just FYI.
