### ISSUE TITLE
Theme Park not working

### ISSUE THREAD

**Issue by spidymame** [ahezard/nds-bootstrap#464] opened 2018-12-02 01:34 UTC
Hi,
just wanted to let you guys know that Theme Park doesnt load on nds-bootstrap, it just gets to solid black screens and doesnt move from there, hopefully it will work someday :)

**Comment by RocketRobz** [comment] 2018-12-02 01:37
What SDK version does the game use?
You can check by pressing Y on the game in the ROM menu of TWiLight Menu++.

**Comment by spidymame** [comment] 2018-12-02 01:39
im using the forwarder instead of the menu system, can i check from there?

**Comment by RocketRobz** [comment] 2018-12-02 01:45
nope

**Comment by spidymame** [comment] 2018-12-02 01:46
ok, ill have to install it, may be a few days, sorry, will get back to you with sdk version soon

**Comment by spidymame** [comment] 2018-12-18 13:36
hi, sorry it took so long, it used sdk version: 3

**Comment by spidymame** [comment] 2019-01-20 12:31
just wondering if this will be added to the compatibility table?

**Comment by ahezard** [comment] 2019-03-04 23:58
I was not able to reproduce any performance issue with the latest nightly, please retest

**Comment by spidymame** [comment] 2019-03-31 03:25
sorry for the radio silence, tested on v 0.17.0 and v 0.17.1 and i feel the load time is slightly reduced and but obviously still hangs for me in spots, the opening it seems most apparent, and clicking new game has it just on a black screen

**Comment by ahezard** [comment] 2019-07-03 21:24
Please test with latest nightly and report if the issue is fixed now that #517 have been implemented

I am still not able to spot any obvious slow down that affect the gameplay. Which region is you game?

**Comment by spidymame** [comment] 2019-09-22 11:40
hi,
finally tried it again and replaced sd card files :) boots like a dream, it boots in chinese text, just gonna try ad figure my way around that, unless you guys know how to get around that one haha

**Closed** 2019-09-24 21:43 UTC
Labels: Cannot reproduce, Performance, Retail
