### ISSUE TITLE
Eyeshield 21 Max Devil Power White Screen

### ISSUE THREAD

**Issue by derrysan7** [ahezard/nds-bootstrap#575] opened 2019-03-24 17:13 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.17.1
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Eyeshield 21 Max Devil Power

### Expected behaviour

Game loads into title screen

### Actual behaviour

Stuck on white screen

### Steps to reproduce

1. Launch the game
2. Twilight Menu++ says it succesfully created the save data
3. White screen

### Other notes
Release Number : 0301

**Comment by RocketRobz** [comment] 2019-04-19 01:15
Can you check if the issue is fixed with both latest TWLMenu++ and nds-bootstrap?

**Comment by derrysan7** [comment] 2019-04-23 14:40
Nope, still white screen, using the latest 0.18.0 nds bootstrap release and latest 8.0.1 twilightmenu++ release

**Comment by ahezard** [comment] 2019-05-17 20:32
Fixed by holding L

**Comment by ahezard** [comment] 2019-05-17 20:33
Game id AE4J

**Comment by ahezard** [comment] 2019-05-17 20:34
Can be fixed at twilightmenu level

**Comment by RocketRobz** [comment] 2019-05-17 20:44
Done.

**Closed by RocketRobz** 2019-05-17 20:44 UTC
Labels: Bug, Needs Testing, Retail
