### ISSUE TITLE
Controls frozen on save selection screen: Mario & Luigi Bowser's Inside Story

### ISSUE THREAD

**Issue by OmeletHopper** [ahezard/nds-bootstrap#249] opened 2018-06-25 02:44 UTC
The game starts up perfectly fine, then when you get to the save file selection screen all controls lock up. The music still plays and the animations continue, however.

**Comment by OmeletHopper** [comment] 2018-06-25 02:50
Also, going into the Mic Test simply freezes on a white screen.

**Comment by mariogamer2** [comment] 2018-06-25 02:53
Same

**Comment by LuisSant** [comment] 2018-06-28 21:18
The nds bootstrap does not support that game, but it can boot it
Check the nds bootstrap compatibility list to see what games work

**Comment by OmeletHopper** [comment] 2018-06-29 15:31
With the XPA patch, I can move around the save selection screen, but when I start a new save file, It black screens. Also, the mic screen still freezes on white. Perhaps I'm not patching it correctly? I got it [from here](https://www.odrive.com/s/8443cc3a-862e-41d7-b064-09378f79f6b3-5965a89a/XPA's+Game+Patches/Mario_and_Luigi_Bowsers_Inside_Story_USA_CRACK_NDS-XPA). @mariogamer2 can you try this?

**Comment by mariogamer2** [comment] 2018-07-01 10:09
I might not be able to do so. I travlled not so long ago.

**Comment by hubert-skowronek** [comment] 2018-07-19 21:52
@OmeletHopper it's the same for me, game hangs on black screen after selecting save

**Comment by Robz8** [comment] 2018-08-16 20:27
We actually tried that a while back, when we we're trying to fix some issues with HGSS, but seemed to not fix it.
I've now added the fix back.

Can you see if [this](https://github.com/Robz8/DSiMenuPlusPlus-update/raw/master/nightly-bootstrap.nds) bootstrap build fixes the issue?

**Comment by hubert-skowronek** [comment] 2018-08-16 20:56
@Robz8 unfortunately clean rom still doesn't work. The questions I ask myself are:
- does game trigger some additional AP measures besides below 8000h reads?
-  is overlay "overlay_0138.bin" loaded properly when the game is ran through nds-bootstrap? (if you will fill overlay 138 with zeroes then the game behaves like AP is triggered and the game doesn't even attempt to read below 8000h, this overlay seems to contain both AP logic and game logic handling save menu)
- does nds-bootstrap return the correct value/passes proper value in src variable containing the address? Forgive my skepticism, it is because I don't know how to debug nds-bootstrap, added chunk of code seems to be correct (with exception that desmume implements it as < 8000h, not <=); the game attempts to read something at the address 1000h at first (if I make hardcoded fix then it stops to read anything more below 8000h but mentioned branch still prevents game to work, I hope I will be able to deal with it and then try to run the game on no$gba to check whether getting rid off below 8000h reads really saves the day [on desmume with turned off below 8000h redirection and changed troublesome branch during the runtime, it does)

**Comment by Robz8** [comment] 2018-08-16 20:59
Some card reads are done from overlays, and those aren't patched, which is why the AP is still triggered.

**Comment by hubert-skowronek** [comment] 2018-08-16 21:29
@Robz8 will be ever possible for nds-bootstrap to patch card reads from overlays? In BIS case the 8000h below reads are in fact from this particular overlay. Anyway, why overlays are somehow exceptional for nds-bootstrap? I thought they are just loaded into memory, overriding memory areas as specified in y9.bin - could you tell me more why technically it is some obstacle for nds-bootstrap?

**Comment by ahezard** [comment] 2018-08-16 21:36
Card read from overlays? I did not know this kind of stuff existed! A read below 8000h into an overlay is clearly an AP measure.
nds-booststrap loads the arm9/arm7 bimnaries and patches the card read functions before the game is runned. Overlays are loaded dynamically while the game is running so this makes it much harder to patch.

**Comment by Robz8** [comment] 2018-08-16 21:37
The card reads are patched before the game is even booted, so as a result, it doesn't affect the overlays, which are loaded after the game is booted.
To work around that issue, we would have to pre-cache the overlays into the RAM cache before booting the game, and then do the patching in the overlays.

**Comment by hubert-skowronek** [comment] 2018-08-16 22:14
@ahezard unfortunately it does exist, and it happens to do rather nasty things: overlay is initially loaded but it consists of functions which transforms part of memory into target instructions which prepare read command at 0x40001A8.

@Robz8 Am I correct in that if I even successfully patch BIS (hardcoded redirection of card reads in overlay) then it won't work with nds-bootstrap? I mean - any game with card read in overlay whether it is below 8000h or not won't work with nds-bootstrap, right?

**Comment by piratesephiroth** [comment] 2018-08-17 04:42
couldn't this be achieved simply by fixing the cheat engine?

**Comment by piratesephiroth** [comment] 2018-08-17 11:54
@hubert-skowronek , I believe it's a combination of both (I can't really know because they're not open source) but take  YSMenu as an example. It contains a file called extinfo.dat that that fixes compatibility with games. It is a basically a database of AR Codes, only they're stored as binary blobs instead of multiple 32 bit values.

**Comment by hubert-skowronek** [comment] 2018-08-17 16:14
@Robz8 @ahezard @piratesephiroth Minor update - today I was able to patch M&L: BIS successfully! However "successfully" means that patched rom works on forked desmume with below 8000h reads disabled. It still doesn't work for some reason on no$gba, I wonder why. I've tried my patched rom with nds-bootstrap and it behaves just the same like the patch provided in Robz8's folder with AP patches. The save menu becomes playable, but after choosing save slot the game hangs on black screens, even though it proceeds further on my forked desmume.

The patches are as follow:
overlay 138:
0x6F4 : 7870010A -> 7870011A

overlay 139:
0x054 : 10FF2F01 -> 0000A0E1

I've applied those patches on decompressed overlays, modified y9.bin so they could be left decompressed and packed the rom.

I will prepare patch file later - @Robz8 , @ahezard would you be able to debug the game then and check what causes the game to hang on black screens?

**Comment by Stack3r** [comment] 2018-08-17 16:27
Does the game load with ysmenu?

**Comment by hubert-skowronek** [comment] 2018-08-17 16:42
@Stack3r No idea, do you ask whether my patched rom works with ysmenu using some flashcard? I don't have any - could you check it using the patch I've provided?

**Comment by ahezard** [comment] 2018-08-17 17:31
I am not sure the cheat engine will be able to fix this. And even if it works it will not be a convenient way to do it. You would have to implements the card read patch which as an ar code, but card read patch exact code are dependent of the nds-boostrap version you are using. Some jump offset at least would slightly change so it would be a mess to maintain.

**Comment by piratesephiroth** [comment] 2018-08-22 19:42
well, the frozen controls can be easily bypassed with a cheat but the game gets stuck in a black screen afterwards, heh

**Comment by hubert-skowronek** [comment] 2018-08-22 20:08
@piratesephiroth I think that's because of unpatched overlays, as @Robz8 suggested :( I am wondering whether not working Golden Sun DD, Lufia and M&L BiS have that in common - unpatched card reads in overlays/another things needed to be patched. @Robz8 , @ahezard are there any plans to implement patching for overlays?

**Comment by Robz8** [comment] 2018-08-22 20:09
Would be nice, but we don't want to get into any trouble with Nintendo. :P

**Comment by piratesephiroth** [comment] 2018-08-22 20:28
uh? do the overlay patches contain copyrighted code?

**Comment by hubert-skowronek** [comment] 2018-08-22 20:29
@Robz8 how it differs from patching, let's say, arm9.bin?

**Comment by Robz8** [comment] 2018-08-22 20:31
@piratesephiroth Nope.
The issue is if nds-bootstrap itself does the patching to the ROMs on the fly to remove AP measures.

**Comment by piratesephiroth** [comment] 2018-08-22 20:35
what? So it's all because it's a Nintendo game?

**Comment by hubert-skowronek** [comment] 2018-08-22 20:36
@Robz8 couldn't we solve it that way that the user has to patch the game on his/her own and nds-bootstrap patches all those things (mainly card reads) as it does with arm9.bin?

**Comment by piratesephiroth** [comment] 2018-08-22 20:52
I was checking WoodR4's source and saw the patch.
It's not really much different from other games however if I tried to apply it on nds-bootstrap, the game gets stuck in a white screen.
So I can only guess nds-bootstrap handles the rom in a different manner.

**Comment by Valeri0p** [comment] 2018-08-23 16:47
IIRC @shutterbug2000 made some partial patches some time ago, maybe he can contribute to the discussion.

**Comment by hubert-skowronek** [comment] 2018-08-24 22:43
I've done small investigation on overlays (searched for end signatures of card reads, dma reads, card cached reads) and found none - the conclusion is that black screen is some other bug than non patched card reads in overlays or maybe those card reads in overlays are prepared dynamically (just like AP code)

**Comment by piratesephiroth** [comment] 2018-08-25 03:10
The thing is that if you look in Wood R4's code, it's really nothing special. It just decompresses the arm9 binary and applies a patch. There's also a similar AP patch in the cheat databases. 

So I can only conclude that nds-bootstrap either lacks some generic AP bypass feature that flashcards have or it just does something different that trigger a new AP check.

**Comment by hubert-skowronek** [comment] 2018-08-25 19:08
@Robz8 I've forked nds-bootstrap and tried to experiment with the redirection of below 8000h reads - it appears that during loading M&L BiS the condition src <= 8000 isn't evaluated to true even once  (compiled quick version of nds-bootstrap which should fall into endless loop if that condition evaluated to true, but it never happens). Could you please tell me how can I run nds-bootstrap via no$gba in order to debug it in more detail?

**Comment by piratesephiroth** [comment] 2018-08-25 20:32
Well I can run nds-bootstrap on no$gba if I install Unlaunch however the games don't actually start,.
They always stop after the loading screen

**Comment by hubert-skowronek** [comment] 2018-08-25 20:36
@piratesephiroth it's too bad then, because I wanted to check what values are assigned to "src" variable in arm9/source/cardengine.c - the work on that project seems to be really hard when it comes to debugging!

**Comment by piratesephiroth** [comment] 2018-08-25 20:41
yeah, the only way I found to verify things was by enabling logging in the iin and using dbg_printf and dbg_hexa to print stuff to the log file.

**Comment by piratesephiroth** [comment] 2018-08-25 20:45
I suppose there is a proper way to debug this but I guess it's a secret to everytone

**Comment by hubert-skowronek** [comment] 2018-08-25 20:45
@piratesephiroth if I am correct it isn't the case for cardengine.c in which debugging seems to be done via nocashmessages? I tried to meddle with that code so I could use dbg_printf but I was told by compiler that there is problem with .elf file and code wouldn't fit in VRAM

**Comment by piratesephiroth** [comment] 2018-08-25 20:50
what? I just tried and it got compiled fine without any errors.

**Comment by hubert-skowronek** [comment] 2018-08-25 20:51
@piratesephiroth and does it write to the file without problems? Could paste code changes in the comment?

**Comment by piratesephiroth** [comment] 2018-08-25 20:53
I'll test it, hang on

**Comment by piratesephiroth** [comment] 2018-08-25 21:31
guess we'll have to wait for the solution to debug this on no$gba

**Comment by RocketRobz** [comment] 2018-12-13 04:08
Now works as of v0.13.0.
AP-patch is still needed.

**Closed by RocketRobz** 2018-12-13 04:08 UTC
Labels: AP Issue, Retail

**Comment by TKDarkWolf** [comment] 2019-07-13 11:25
@RocketRobz I know this is post is a little old, but if you see this, can you send a link to a tool so I can AP-patch BIS.  I tried looking over google, but the threads that have answers don't have working links to the downloads.

**Comment by arraystock** [comment] 2019-07-14 16:00
Use the kinder_bueno patch from [here](https://www.odrive.com/s/8443cc3a-862e-41d7-b064-09378f79f6b3-5965a89a), and use an xdelta patcher, like [this one](https://www.romhacking.net/utilities/704/).

**Comment by TKDarkWolf** [comment] 2019-07-19 11:19
Thank you for the help, I was able to get Kirby Mass Attack and BIS AP patched, but I couldn't find a patch for Golden Sun in the odrive list, so if you know where to find one, I would appreciate it very much.

**Comment by thesmartie** [comment] 2019-07-28 19:31
@arraystock when i try to use that program i get an error wich says: An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT. do you have an idea to fix this?

**Comment by arraystock** [comment] 2019-07-31 18:14
Hmm, I’m not sure. I would make sure there are no spaces in any of the paths, or at least quote the paths (`"C:\my directory\like this"`), but beyond that I might not be able to help you.

**Comment by MasterGamingYT** [comment] 2019-08-01 04:00
You might as well find another patcher
