### ISSUE TITLE
Alternative for Async Prefetch or increase stability? 

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#376] opened 2018-08-19 18:55 UTC
So IIRC this technique of loading was put in place to fix audio issues but on the down side it breaks certain games, would there be a better alternative for this or is there a way to fix the compatibility issues that this causes?

**Comment by Robz8** [comment] 2018-08-20 04:43
Async prefetch can be turned off for those games with issues caused by it.

**Comment by Stack3r** [comment] 2018-08-20 04:49
But where would that leave audio quality for those games?

**Comment by ahezard** [comment] 2019-01-09 08:33
So the non blocking io code that have been merged is exactly an alternative to async prefetch that inproved performance and fixed audio issue. But that does not means prefetch cannot be retroduced. The non blocking io code uses properly the ndma dsi unit to almost completely offload the sdmmc read workload from the arm7 cpu. Async prefetch was a mechanism to preload data on arm7 side without involving the arm9 but such technique with the new non blocking io would probably be much more efficient. Now it is needed to understand also if it is needed : if all games run full speed, at some point it became useless to optimise performance further.

**Closed** 2019-03-06 18:09 UTC
Labels: Enhancement, Performance
