### ISSUE TITLE
game crashing 

### ISSUE THREAD

**Issue by fuckyouyu** [ahezard/nds-bootstrap#682] opened 2019-06-20 21:01 UTC
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen
i select the side game (i.e new soup's minigames) and i go to the minigames menu 
### Actual behaviour

Tell us what happens instead
the screen goes to a black screen and nothing happens 
### Steps to reproduce

1.
2.
3.

**Comment by arraystock** [comment] 2019-06-20 22:58
The mini games not loading is due to soft resetting. Duplicate of #259

**Comment by NightYoshi370** [comment] 2019-06-20 23:18
Closing due to alt issue.
BTW, please make your title, ya know, descriptive.

**Closed by NightYoshi370** 2019-06-20 23:18 UTC
