### ISSUE TITLE
it still isnt saving

### ISSUE THREAD

**Issue by snes666** [ahezard/nds-bootstrap#537] opened 2019-02-16 15:58 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by snes666** [comment] 2019-02-16 15:59
it still isn't  saving with ram disk what should i do????????
@RocketRobz

**Comment by RocketRobz** [comment] 2019-02-16 15:59
Duplicate of #520

**Comment by RocketRobz** [comment] 2019-02-16 15:59
This isn't an issue you can fix.

**Closed by RocketRobz** 2019-02-16 15:59 UTC
