### ISSUE TITLE
Mario Kart DS Freezes in the first race

### ISSUE THREAD

**Issue by Reynaldo241** [ahezard/nds-bootstrap#308] opened 2018-07-12 21:34 UTC
Console.- O3DS with luma 9.0
Nds Bootstrap 0.10.1 with dsimenu++ 5.1.0, loading via dsi menu launcher 1.1
Rom Region.- USA

In the Lightning cup, the Snes Choco Island course freezes the game, randomly occurs in middle race, this only happens on GP, in time trials the course doesn't freeze

Edited: any CC

**Comment by CecilFF4** [comment] 2018-07-16 03:08
Freezes in TT and GP for me. Only Choco Island 2. O2DS.

**Comment by Sagametroid** [comment] 2018-07-16 03:50
sometimes is possible spawn out of bounds XD

**Comment by CecilFF4** [comment] 2018-07-16 05:36
On an O2DS, it doesn't matter if I set the game to TWL or NTR speed.

**Comment by Stack3r** [comment] 2018-07-16 05:40
Can confirm it freezes loading time trial on N3DS

**Comment by Reynaldo241** [comment] 2018-07-16 05:51
I've tested with NTR speed and tt/cc freezes, but in TWL it doesn't freeze in tt, only in cc

**Comment by MarioKartFan** [comment] 2018-07-21 20:45
I get a white screen whenever loading the Lightning Cup.  Otherwise, the game seems to work perfectly.

**Comment by NoMod-Programming** [comment] 2018-07-21 20:55
@MarioKartFan Which model DS are you using? I'm using a DSi with no issues. I'm thinking that it might be a 2ds/3ds issue.

**Comment by MarioKartFan** [comment] 2018-07-21 20:57
@NoMod-Programming I am using a New 2DSXL.

**Comment by Robz8** [comment] 2018-07-21 20:57
@MarioKartFan What is your nds-bootstrap version?

**Comment by MarioKartFan** [comment] 2018-07-21 20:59
@Robz8 I have tried it with the latest version on the New 2DSXL.  Also had this problem on a 3DS using 10.0 and 10.1.

**Comment by Robz8** [comment] 2018-07-21 21:00
Might be an issue with how nds-bootstrap is reading the ROM loaded into RAM.
Try re-packing the ROM using dalazy.

**Comment by MarioKartFan** [comment] 2018-07-21 21:04
@Robz8 Very grateful for the feedback.  Not sure where to locate dalazy.  I have not heard of that particular utility before, and some quick Google searches is not turning anything up.  Thanks.

**Comment by Robz8** [comment] 2018-07-21 21:05
Oh, spelling error.
I meant DSLazy.

**Comment by MarioKartFan** [comment] 2018-07-21 21:15
@Robz8 You are a genius.  Repacking fixed it.

**Comment by Reynaldo241** [comment] 2018-07-22 04:46
It seems to works without problems after repacking,  Thanks!

**Comment by dubbz82** [comment] 2018-07-22 15:51
If this is happening from a clean rom dump, yeah this should still stay opened.  If this is from a trimmed rom or something that's otherwise been somehow modified, maybe not?

**Comment by Robz8** [comment] 2018-08-04 04:45
Can any of you see if the issue is fixed in [this](https://github.com/Robz8/DSiMenuPlusPlus-update/raw/dd4f7518ec4024f62d1f73c82a49d210a14392a0/nightly-bootstrap.nds) nightly bootstrap build?

**Comment by Reynaldo241** [comment] 2018-08-05 04:11
Still freezes on the non-repacked rom

**Comment by Antonio231102** [comment] 2018-11-01 06:04
Just like @MarioKartFan, my game freezes after selecting Lightning Cup. Unpacking and repacking the ROM using DSLazy like @RocketRobz said completely fixed the issue; 3 star rank, here I go!
I hope this issue gets fixed soon as it looks like it's been a while since it was first documented

**Comment by RocketRobz** [comment] 2018-12-04 16:56
Can any of you send a save with Lightning Cup unlocked?

**Comment by RocketRobz** [comment] 2018-12-04 17:34
Ok, I encountered the crash as well.
Hopefully I can fix this. :P

**Closed** 2019-01-05 00:52 UTC
Labels: 3DS, Bug
