### ISSUE TITLE
Cannot host single-card Download Play games to other hardware

### ISSUE THREAD

**Issue by 5kyl4rk** [ahezard/nds-bootstrap#515] opened 2019-01-29 23:35 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- N/A

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[17.0]_
- [ ]  Nightly _[N/A]_

### Expected behaviour

Hosting a simple Download Play game using TWiLightMenu/NDS-Bootstrap should allow for an actual DS (or 3DS) console to join via the Download Play

### Actual behaviour

The option to join is available on the original hardware, when "downloading" the connection bars are green until the original hardware tries to boot the game; the Nintendo logo appears but connection gets lost and freezes and the host is then notified.

### Steps to reproduce

1. Host a multiplayer game using the "without a cartridge" option on an nds-bootstrap frontend
2. Open an original DS handheld (or 3DS) and click on the DS Download Play and join the game that appears
3. Host system starts connection for multiplayer
4. Connection starts but crashes shortly afterwards before the original DS can boot the downloaded game

### Other notes
1. Multiplayer will work if the original console joins using the physical cart
1. You can host a single-card game on the original console and join using DS Download Play on bootstrap but not vice versa
1. At first I thought it was a problem for all games, but it would appear that this only effect _some_ games with very little indication on which ones will work.  The only pattern I've seen is that it mainly effects first-party games.

Currently these are the games I have tested:
  - Mario Kart DS = only works for multi-card hosting 
  - Diddy Kong Racing DS = cannot host simple download play, should in theory work with multi-card
  - Mario Party DS = cannot host since it requires download play regardless of having multiple copies
  - Super Mario 64 DS = cannot host 
  - New Super Mario Bros. = cannot host
  - Kirby Super Star Ultra = hosting works for both multi-card and simple
  - Kirby Squeak Squad = cannot host (game itself crashes before the option is available)
  - Starfox Command = hosting works
  - LoZ: Phantom Hourglass = hosting works
  - LoZ: Spirit Tracks = hosting works
  - Brain Age = hosting works
  - Ridge Racer DS = hosting works
  - Burnout Legends = hosting works
  - TrackMania Turbo = hosting works
  - Sonic Rush = hosting works
  - Sonic Rush Adventure = hosting works
  - Yoshi Touch & Go = cannot host
  - Tetris DS = hosting works
  - CoD 4 Modern Warfare = cannot host
  - Metroid Prime Hunters = cannot host
### See also
#319, #496

**Comment by ahezard** [comment] 2019-03-03 20:25
So this is link to cloneboot

**Comment by ahezard** [comment] 2019-03-03 20:26
Caused by #553

**Comment by NightYoshi370** [comment] 2019-03-20 13:17
This is linked to cloneboot and as such, please follow the original issue found at #553 
Closing

**Closed by NightYoshi370** 2019-03-20 13:17 UTC
Labels: Enhancement, Retail
