### ISSUE TITLE
New Super Mario Bros DS: Minigame mode not working

### ISSUE THREAD

**Issue by Volti-p** [ahezard/nds-bootstrap#358] opened 2018-08-09 23:24 UTC
Is it possible, to make the minigame Mode work in the future? :)

**Comment by Robz8** [comment] 2018-08-21 01:17
Turns out it's not working, due to it trying to restart the system, which is not patched.
Games that require going back to the title screen after certain commands stay at a black screen.
[image](https://cdn.discordapp.com/attachments/283769550611152897/481258582424158229/unknown.png)
(credit to Skawo for the image)
That would presumably be why they don't work.

**Comment by Stack3r** [comment] 2018-08-21 02:14
@damianoamatruda any ideas on patching reboots?

**Comment by YYoshi241** [comment] 2018-08-21 20:34
(Somewhat Related) SM64DS Minigames do work. So until NSMBDS minigames are fixed we can use SM64DS to play many of the same minigames. 

Also: Maybe since the minigame mode was ported from SM64DS, we could use that game to help troubleshoot?!

**Comment by NightYoshi370** [comment] 2018-08-21 20:49
i thought the same, but the issue is completely seperate

**Comment by viggou** [comment] 2019-02-20 18:25
If we can find out how SM64DS loads it wouldn't it be possible to patch NSMB to do it the same way?

**Comment by dubbz82** [comment] 2019-03-03 20:40
Tied to #259

**Comment by Stack3r** [comment] 2019-03-06 18:08
Closing this due to soft reset being the issue and not the game itself

**Closed by Stack3r** 2019-03-06 18:08 UTC
Labels: Enhancement, Retail
