### ISSUE TITLE
ermii kart ds beta 1-r crashes at boot 

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#385] opened 2018-08-21 21:17 UTC
When playing Ermii Kard DS Beta 1-r, I get a crash at the boot screen, independent of any settings. I am using nds-bootstrap v12.3.2 pr1 and TWLMenu++ 6.6.1 on my o3DS XL.
![0821181707_hdr 1](https://user-images.githubusercontent.com/36418671/44429287-e6113480-a564-11e8-9c83-28d5d1f4722d.jpg)

**Comment by YYoshi241** [comment] 2018-08-26 01:26
Still occurs on 11.1

**Comment by YYoshi241** [comment] 2018-09-13 06:04
Still occurs on 11.2

**Comment by YYoshi241** [comment] 2018-09-24 18:06
Still occurs on 12.1 r2

**Comment by NightYoshi370** [comment] 2018-12-04 20:07
In the future, no need to spam the comment section for which version you're using. Just edit the first post.

I think this is a duplicate of another thread, but let me make sure

**Comment by poudink** [comment] 2018-12-04 22:21
it probably is. this issue has been known since the dawn of time. I heard Ermii Kart DS beta 2 will be compatible with nds-bootstrap, whenever beta 2 releases anyway.

**Closed** 2020-03-19 00:37 UTC
Labels: Bug, Future Work, ROM Hack

**Comment by qamichele59** [comment] 2021-06-05 17:41
Unplayable due to gets the error dump screen
