### ISSUE TITLE
DS Download Play Functionality

### ISSUE THREAD

**Issue by ChromoTec** [ahezard/nds-bootstrap#319] opened 2018-07-15 23:54 UTC
Versions: Both 0.10.1 release and latest nightly

Console: DSi XL

CFW: HiyaCFW, running DSiMenu++
Download Play does not work with any game. It did work before with all of my games, but now the secondary console (joining the game from DS Download Play) will always get stuck at the Nintendo logo, and the host console will get a "communication error occurred" message. This is not a problem with the console, as a physical copy of a game works just fine in Download Play.

**Comment by Robz8** [comment] 2018-07-15 23:59
This issue doesn't occur with all games.
Bomberman does not have this issue, as it does not use cloneboot for DLP.

**Comment by ChromoTec** [comment] 2018-07-16 00:32
Is there any fix? And how do I tell if a game uses cloneboot for DLP?

**Comment by Robz8** [comment] 2018-07-16 00:39
If the secondary console freezes at the Nintendo logo, then the game uses cloneboot.
Can you try v0.10.0?

**Comment by ChromoTec** [comment] 2018-07-16 01:12
I used Super Mario 64 DS, Mariokart DS and Marioparty DS. I will get back to you on whether v0.10.0 works.

**Comment by ChromoTec** [comment] 2018-07-16 01:18
No, v0.10.0 has the same error.

**Comment by NoMod-Programming** [comment] 2018-07-16 05:33
I can't find any information on cloneboot online. Any way to describe roughly what it is and how it differs from other multiplayer types?

**Comment by TomSputz** [comment] 2019-01-23 15:03
I'd like to help work on this if possible - any pointers as to what might've caused this to break in v10?

**Comment by ChromoTec** [comment] 2019-01-23 16:19
Not sure. It _usually_ doesn't work, but every once in a while it will magically work for one game. I've also noticed that it only happens on games that require cloneboot for DLP.

**Comment by ahezard** [comment] 2019-03-03 20:28
This is caused by #553

**Comment by NightYoshi370** [comment] 2019-03-20 13:16
This is somewhat of a clone of #553.
Closing

**Closed by NightYoshi370** 2019-03-20 13:16 UTC
Labels: Enhancement, Retail
