### ISSUE TITLE
The World Ends With You crashes on opening scene

### ISSUE THREAD

**Issue by afdc98** [ahezard/nds-bootstrap#235] opened 2018-06-23 11:17 UTC
The game just crashes in the middle of the opening scene (just after the first tutorial fight). I've tried twice and it seems to be a consistent issue (0.9.2). I'm using DsiMenu++ in a N2DSXL, thank you.

**Comment by Kalanyr** [comment] 2018-06-23 11:39
Have you tried AP patching it ?

**Comment by afdc98** [comment] 2018-06-23 13:20
I don't know how to do that... sorry. I've tried with a program called DS-Scene Rom Tool but it won't let me, claiming the rom isn't in the ap database

**Comment by ahezard** [comment] 2018-06-23 13:44
thanks for the link so the only issue here is speed, this is an interesting test case.
FF3 opening intro also crash due to speed, which is a similar issue.

What can be done eventually is to restore the whitelist mechanism, but I want to do it properly : preload the cache with data on the bootloader, not by creating another cache area like what was done by @Robz8

**Comment by MojoJojoDojo** [comment] 2018-06-23 13:49
I thought FF3 opening dont work because of this https://mgba.io/2017/07/31/holy-grail-bugs-2/.
Thats not the same issue as the world ends with you because that works in emulators just fine.

**Comment by ahezard** [comment] 2018-06-23 13:59
nds-boostrap is not an emulator, it cannot crash due to imprecise emulation or bad timing. The only thing that can made it crash is card read speed or some deadlock between arm7 and arm9 during the card read execution (card read in nds-bootsrap uses the arm7 which is different from normal card read that can be executed indepandantly by arm9). 

In previous release the FF3 intro was put in RAM before the execution of the game and it worked flawlessly, I do not see why the same trick cannot solve The World Ends With You issue.

**Comment by SpikeValantine** [comment] 2018-06-24 21:07
Try playing the first tutorial fight on an emulator like no$gba or Desmume and then copy the save game onto your DS.
Not a solution but a valid bypass.
I've played TWEWY without any problems since 0.91.

**Comment by ahezard** [comment] 2018-06-26 22:46
One user on discord reported to not have this issue using a rom from another region. Can someone confirm that?

**Comment by Stack3r** [comment] 2018-06-26 23:19
I can also play the game without issues, gotten past the first battle too

**Comment by Stack3r** [comment] 2018-06-28 02:16
Closing this issue for now

**Closed by Stack3r** 2018-06-28 02:16 UTC

**Comment by tranxuanthang** [comment] 2018-07-10 12:39
I have this issue too. DSIMenu++ with nds-bootstrap 0.10.1. I tried reformating my sdcard with FAT32 - 32KB cluster size but still no luck. Using repeatly-close-and-open-3ds trick is not work either (or I was doing it wrong). My solution is that using a save to bypass this, I found one [here](https://filetrip.net/nds-downloads/game-saves/download-2230-twewt-ds-x-save-game-f2025.html) when searching on gbatemp and it works, and I still haven't seen any freezes yet.

**Comment by Joseph3919** [comment] 2020-06-25 02:20
I had this problem as well but I believe I've fixed it. I messed around with DSiMenu++'s settings and tried increasing the clock speed and changing it to dsi mode rather than ds mode and then it worked perfectly fine. I've only played a bit of the game so far so I'm not sure if it'll hold but it hasn't crashed yet

**Comment by zaloh** [comment] 2020-12-02 19:04
I can confirm forcing the game into DSi mode fixes the crash for me.
