### ISSUE TITLE
Crash when selecting "Save and Quit" option in Bowser's Inside Story

### ISSUE THREAD

**Issue by shutterbug2000** [ahezard/nds-bootstrap#473] opened 2018-12-13 21:19 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release v0.13.0
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Mario and Luigi: Bowser's Inside Story

### Expected behaviour

Game should go to the intro

### Actual behaviour

White screen

### Steps to reproduce

1. Hit a save block
2. Select save and quit

### Other notes:
Likely related to soft-reset being broken.

**Comment by Stack3r** [comment] 2019-02-27 13:46
Is this still an issue?

**Comment by NightYoshi370** [comment] 2019-03-01 18:12
Should be, as soft-reset hasn't been patched out yet IIRC

**Comment by ahezard** [comment] 2019-03-03 20:22
This is caused by #259

**Comment by NightYoshi370** [comment] 2019-03-18 02:57
Closing this due to soft reset being the issue and not the game itself

**Closed by NightYoshi370** 2019-03-18 02:57 UTC
Labels: Enhancement, Retail
