### ISSUE TITLE
Professor Layton and the Curious Village won't load the upstairs of Reinhold Manor

### ISSUE THREAD

**Issue by RingedWizard** [ahezard/nds-bootstrap#753] opened 2019-09-24 22:31 UTC
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release [v0.24.1]
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Professor Layton and the Curious Village

### Expected behaviour

After reaching Reinhold manor for the first time, You're supposed to go upstairs and proceed with the game

### Actual behaviour

 Going upstairs fades to the usual black loading screen but never proceeds

### Steps to reproduce

1.Reach Reinhold Manor
2.Solve the puzzle youre forced to do
3.proceed upstairs

**Comment by RocketRobz** [comment] 2019-09-24 22:32
What version of TWLMenu++ are you using?

**Comment by RingedWizard** [comment] 2019-09-24 22:35
v9.5.0 i just updated it today

**Comment by ahezard** [comment] 2019-09-25 18:49
Can you please upload a save file that would allows to reproduce the issue?
Thanks for reporting the issue.

**Comment by RingedWizard** [comment] 2019-09-25 21:37
attached is my save file, shortly before uploading i updated the twilightmenu on my dsi and tried it on that with the same results as the 3ds 

[Professor Layton and the Curious Village save.zip](https://github.com/ahezard/nds-bootstrap/files/3654889/Professor.Layton.and.the.Curious.Village.save.zip)

**Comment by RocketRobz** [comment] 2019-10-14 14:23
Probably another issue related to card read DMA.

**Comment by RocketRobz** [comment] 2019-10-23 04:12
Seems to be fixed in later releases.

**Closed by RocketRobz** 2019-10-23 04:12 UTC
Labels: Bug, Cannot reproduce, Retail
