### ISSUE TITLE
Geometry Wars Galaxies

### ISSUE THREAD

**Issue by dubbz82** [ahezard/nds-bootstrap#264] opened 2018-06-30 03:02 UTC
The US region of Geometry Wars Galaxies has significant glitching going on with the background graphics at boot and locks at the title screen.  This game does not have any known AP, so AP patching most likely is not the cause.  Tested with 10.0 Release build.

**Comment by ahezard** [comment] 2019-03-03 17:46
The issue is confimed on master. The glitching  persist on the main menu for me.

**Comment by ahezard** [comment] 2019-03-03 17:48
Could be linked to #517 (the game uses dma for card read)

**Comment by ahezard** [comment] 2019-03-03 17:53
dma does not fix the issue

**Comment by ahezard** [comment] 2019-03-03 22:14
probably linked to #554

**Comment by ahezard** [comment] 2019-03-04 23:41
not linked to memcpy issue

**Comment by ahezard** [comment] 2019-05-06 21:49
Fixed in 19.2

**Closed by ahezard** 2019-05-06 21:49 UTC
Labels: Bug, Retail
