### ISSUE TITLE
Final Fantasy XII: Revenant Wings behaving very strangely

### ISSUE THREAD

**Issue by leongunblade** [ahezard/nds-bootstrap#462] opened 2018-11-27 00:19 UTC
So this game is driving me nuts, it refuses to work properly on latest 0.12.3 rev1 of bootstrap. I have been trying to make it work for an entire day and it will randomly boot successfully if you keep trying, while it sometimes either freezes after the first movie or it won't boot at all giving a white screen. Another weird thing is that sometimes it will boot while using the "boot last ROM" from twilight launcher. 

I really hope you can fix this as I've basically installed twilight menu only for this game, trusting the wiki as it said it works while it doesn't.

**Comment by ahezard** [comment] 2019-02-01 00:07
Could be linked to #517

**Comment by ahezard** [comment] 2019-05-15 22:52
Is this still true? I was not able to reproduce it with latest release.

**Comment by JonnyLawless420** [comment] 2019-09-28 21:11
Same problem here and I'm fully updated via the official updater.

**Comment by RocketRobz** [comment] 2019-10-23 04:25
Is this fixed in v0.26.1?

**Comment by dubbz82** [comment] 2019-12-02 02:16
Can you try again on latest?  If it's still problematic, please pull the CRC/SHA-256/etc for the rom, so we can check against it.

**Comment by Kalanyr** [comment] 2020-01-29 15:31
Seems to work fine on the latest release as  of this post, as far as I can tell.  

I can get past the starting movie, the movie after starting a new game, battles seem to work, including summoning Espers. 

I may have missed some things since it's been a long time since I played so my mechanics knowledge is lacking but from a quick look and test it seems fine now.

**Closed** 2020-01-29 15:46 UTC
Labels: Bug, Cannot reproduce, Needs Testing, Performance, Retail
