### ISSUE TITLE
Pokemon B2/W2 work, but BB2/VW2 don't 

### ISSUE THREAD

**Issue by ismailhasannnnnn** [ahezard/nds-bootstrap#321] opened 2018-07-18 06:01 UTC

**Comment by legoj15** [comment] 2018-07-18 08:39
People have already stated this in another issue.

**Comment by ahezard** [comment] 2018-07-25 22:53
Ok so this is a rom hack. What error do you have? white screen? black screen?

**Comment by ismailhasannnnnn** [comment] 2018-07-25 22:54
A white screen

**Comment by Robz8** [comment] 2018-07-25 23:05
Really? I've heard bootstrap's error screen just shows up, which happens for me.
It's a result of bootstrap failing to decompress it's arm9 binary.

**Comment by ismailhasannnnnn** [comment] 2018-07-25 23:09
Well, using DSiMenuPlusPlus, the little loading game just turns red, and everything else is just white

**Comment by Robz8** [comment] 2018-07-25 23:10
Ah, so you have a minigame set as your loading screen.
When the graphics turn red, that means an error has occurred.

**Comment by ismailhasannnnnn** [comment] 2018-07-25 23:11
Ohhh gotcha. Sorry I didn’t know. Is it something that’ll be able to be fixed?

**Comment by damianoamatruda** [comment] 2018-08-14 21:18
Duplicate of #284

**Closed by damianoamatruda** 2018-08-14 21:18 UTC
Labels: ROM Hack, Retail
