### ISSUE TITLE
New Super Mario Bros. Minigames causes dark screen.

### ISSUE THREAD

**Issue by Mikasu-X14** [ahezard/nds-bootstrap#770] opened 2019-10-05 21:26 UTC
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.25.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

New Super Mario Bros.

### Expected behaviour

I expected the minigames menu to load and allow me to play minigames like on DeSmuME.

### Actual behaviour
When selecting "Minigames" in the menu, the screen darkens but stays dark. The key combination to close the rom doesn't work. Pressing HOME will sometimes reboot the console entirely.

### Steps to reproduce

1. Launch a New Super Mario Bros. rom (US or EU, both did that for me)
2. Select "Minigames"
3. Observe the screen go black and nothing happens.

### Other notes
As stated, I tested with USA and EUR roms, not JAP (because I can't read Japanese).
I tested the roms on DeSmuME on my PC to see if they were really working and yet they do.
The roms I used aren't bad roms.

**Comment by RocketRobz** [comment] 2019-10-05 21:27
I think there's an issue already open for that.

**Comment by Mikasu-X14** [comment] 2019-10-05 21:28
> I think there's an issue already open for that.

Maybe I missed it, I scrolled through all the issues and didn't see it. Can you point it?

**Comment by RocketRobz** [comment] 2019-10-05 21:31
Weird. I thought there was an issue already open for this.

**Comment by Mikasu-X14** [comment] 2019-10-05 21:31
there is an issue but it wasn't about minigames

**Comment by Mikasu-X14** [comment] 2019-10-05 21:44
should I test a nds-bootsrap nightly? If yes, which is likely to change the behavior of the game?
- Latest
- edb4aa81
- 7357afa4

**Comment by dubbz82** [comment] 2019-10-08 16:49
If memory serves this is directly caused by soft reset not working currently.  The game actually resets entirely before loading and should be resolved when that is corrected.

**Comment by Mikasu-X14** [comment] 2019-10-08 18:19
I searched a bit and seems like that's the case.

**Comment by Mikasu-X14** [comment] 2019-10-09 19:10
Is the softreset branch dedicated to fixing the the soft reset problem?

**Comment by NightYoshi370** [comment] 2019-12-18 06:16
https://github.com/ahezard/nds-bootstrap/issues/259
Since this isn't an issue with the game itself but rather with the fact that soft-reset isn't implemented yet, we should close this

**Closed by NightYoshi370** 2019-12-18 06:16 UTC
Labels: Bug, Retail
