### ISSUE TITLE
Wario Master of disguise White screen

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#452] opened 2018-10-21 08:16 UTC
Wario Master of disguise doesn't boot it says stuck on a white screen switching from twl to ntr doesn't fix it

N3DSXL Latest FW
B9S Latest
Luma3DS Latest
TWiLightMenu v6.4.3

**Comment by DerpBlerp** [comment] 2018-12-01 16:49
when creating the data for MAster of disguise on the compatibility list someone put USA, instead of Japanese which to my knowledge is the only working version of the game.

**Comment by ahezard** [comment] 2019-03-03 15:29
duplicate of #397

**Closed by ahezard** 2019-03-03 15:29 UTC
Labels: Retail
