### ISSUE TITLE
 Resident Evil - Deadly Silence freezes after You Died scene.

### ISSUE THREAD

**Issue by tranxuanthang** [ahezard/nds-bootstrap#305] opened 2018-07-11 04:09 UTC
Everytime when the "You Died" text shows up, either if you skip it (press B) or don't do anything, the game freezes. Using emulators (like Desmume) doesn't have this problem. I think it relates to how the game restarts itself (soft reset) each time after the player died. Other than that, the game is fully playable so far without any problems.
I've tested with both USA and EUR version of this game.
I'm using DSIMenu++ 5.1.0 (with nds-bootstrap 0.10.1) on a 3DS. I also tried with newest twloader too.
If you need any more information please tell me.

**Comment by RinMaru** [comment] 2018-07-11 04:16
theres audio issues like clipping so no issues is a bit of an overstatement

**Comment by tranxuanthang** [comment] 2018-07-12 08:07
Okay, indeed there are some audio issues. I was playing mostly on 3ds speaker so I didn't realize this. But still it happens rarely and only at some part of the game. I remember the last time I tried RE:DS on TWLoader, I can't even get pass the opening video 😆 and just a few months later almost any games work.

**Comment by RinMaru** [comment] 2019-02-18 15:58
Just encountered the White Screen lockup after dying

**Comment by dubbz82** [comment] 2019-02-18 16:02
Just call it perma death.  No seriously, there's still some issues with games that do soft resets which sounds like what this is.

**Comment by RinMaru** [comment] 2019-02-18 16:21
sounds fair to me lol

**Comment by ahezard** [comment] 2019-03-03 20:21
This is caused by #259

**Comment by Stack3r** [comment] 2019-03-06 18:04
Closing this for now due to soft resetting being the issue and not the game itself

**Closed by Stack3r** 2019-03-06 18:04 UTC
Labels: Enhancement, Retail

**Comment by heldernovais** [comment] 2019-11-07 19:53
Anyone?

**Comment by RocketRobz** [comment] 2019-11-07 19:56
@heldernovais Wait for a fix.
It's not something that can be fixed on your side.
