### ISSUE TITLE
Animal Crossing: Wild World

### ISSUE THREAD

**Issue by maorninja** [ahezard/nds-bootstrap#38] opened 2017-01-26 17:59 UTC
Unfortunately, there is no one willing to hack/debug the game so we don't know exactly what exactly is the problem. Or so you thought...

> This game has a crash debugger triggered similarly to the one in SM64DS and NSMB. This one is a bit less technical and more informative, but a lot less in-depth.

> To access the crash dump screen hold L + R + A + Left, let go, hold Down + B, let go, and finally hold Start + Select.

Nintendo was kind enough to actually put a debug screen inside of the game...

Apparently, for me it works, but the debug steps don't actually work for other users...

Edit: A user by the Name of Lykie did those steps and this is what she saw: 

![Crash Screen](http://i.imgur.com/28Ho6n3.jpg)

**Comment by Lykie** [comment] 2017-01-27 00:22
Perhaps include what region and version of AC:WW you have (if there's been multiple prints of it)?

**Comment by maorninja** [comment] 2017-01-29 19:52
>  it didn't actually boot until latest commit.

This is the story. I just got 3.0, waited 30 seconds and just did the combo...

**Comment by ahezard** [comment] 2017-02-05 18:30
What is strange with Animal Crossing is that my patcher found some offset for the card read function on arm9 but when I try to jump to this offsets using no$gba I found a very different code from what I expect. The game seems to  use some code relocation that causes the read patching to fail.

**Comment by shutterbug2000** [comment] 2017-06-30 03:16
Fixed in the most recent commit. c:

**Closed by shutterbug2000** 2017-06-30 03:16 UTC
Labels: Retail

**Comment by malek78i** [comment] 2018-07-04 10:22
Hey there! The sound in ACWW is cracking and the hour bell rings every 2-3 Minutes. Is it a bug or caused by my DSi?
