### ISSUE TITLE
Golden Sun dark dawn  Stuck on main screen.

### ISSUE THREAD

**Issue by jvhellraiser** [ahezard/nds-bootstrap#450] opened 2018-10-14 02:02 UTC
Been trying to load Golden Sun Dark Dawn and there no success on doing this even with the correct AP patch the game will always get stuck in the main screen with no AP patch is  a Black Screen with the AP patch is a white screen i was wondering  is there has been any progress on loading such games in any way possible?

Golden Sun Dark Dawn (USA) 
Crc32 : 508420E7

AP patch use:
![cover-25vc6](https://user-images.githubusercontent.com/16488761/46911742-12c54500-cf33-11e8-8013-c1ba918c996b.jpg)

Action Replay cheats for AP Fix are:
E23FC400 00000198
E1A05000 E24DD008
E92D403F E2854004
E28D5024 E8950007
E2455008 E28F3004
E885001F E8BD803F
E8BD0004 E92D003F
E8920003 E0801001
E28F20EC E28F3020
E3A04004 E59F5110
EB00001D E28F20E4
E28F303C E3A04008
E3A05000 EB000018
E8BD803F E5802004
E5802000 E58DE004
E92D003F E1A01005
E2410010 E28F20B4
E28F300C E3A04008
E3A05000 EB00000C
E8BDC03F E3A00000
E92D41FF E1A00005
E080100B E28F2098
E28F304C E3A04004
E59F50A4 EB000002
E28F2090 EB000000
E8BD81FF E92D41FF
FA000024 E3500000
0AFFFFFA E0406004
FB000027 E38774EB
E5867000 EE076F3E
E3550000 12466004
15865000 1E076F3E
EAFFFFF2 E58DE004
E92D100F E1A01004
E3510902 33A01902
E3A000B7 E1A00000
E1A00000 E59F2004
E12FFF32 E8BDD00F
02049850 3AFFFFF8
E5802004 E5802000
3AFFFFAE E3A00000
E28DD008 E5C101AD
E5C101AE E5C101AF
E5C211AD E5C201AE
E5C201AF E92DC000
CA1CB5FC D2084288
42AAC8E0 42B3D103
42BCD101 3808D002
2000E7F4 1B9FBDFC
01BF3F08 47700A3F
D2000000 00000000
5204BA64 E1A05000
0204BA64 EB0EC265

I try both but no success any help or news of a incoming fix for this games?

**Comment by jvhellraiser** [comment] 2018-10-14 19:52
Oooh wao this means we will never gonna be able to load this game on the twilight menu, I manage to load Dragon Quest IX - Sentinels of the Starry Skies using DS rom tool Integrated AP Patch Fix. and It loaded pretty nice no issues at all at least until now.

**Comment by RocketRobz** [comment] 2018-10-14 19:54
Never say never. ;)
I'm sure we can get this working.

**Comment by RocketRobz** [comment] 2018-10-14 20:40
@jvhellraiser Try [this](https://github.com/RocketRobz/TWiLightMenu-update/raw/d995ffe21527183d36131bf3cba9ecb788c90285/nds-bootstrap-nightly.nds) nightly build.

**Comment by piratesephiroth** [comment] 2018-10-14 21:17
Nope, it still seems to have something wrong there. Any code that uses that area still makes the game crash.

**Comment by jvhellraiser** [comment] 2018-10-15 01:59
No, it does nothing game + AP patch = Black screen 
Now with Action Replay cheat for AP Fix = Black Screen , first i got a White Screen
RocketRobz you are into something the fix is there but you miss something.
can the code be injected and then be disable before the game notice it?

**Comment by piratesephiroth** [comment] 2018-10-15 02:35
I still get a white screen all the same. I only get a black screen if I don't use the code.

**Comment by jvhellraiser** [comment] 2018-10-15 17:10
I truly don't understand why is it that even with area 0x023FC400 being empty why is so hard to bypass this is it trying to write to another full area?

**Comment by piratesephiroth** [comment] 2018-10-15 17:41
0x023FC400 is one of the areas reserved by the flashcards for their own patches, specifically for games with compressed arm9 binaries, so it is never touched otherwise.

nds-bootstrap clearly wasn't developed with that in mind and is using that space for somehting else.

**Comment by jvhellraiser** [comment] 2018-10-15 23:49
i was wondering can nds-bootstrap imitate Bios or Twilight menu ++ (Imitate) maybe these games are asking for a bios check before it loads.

**Comment by RocketRobz** [comment] 2018-10-16 00:11
The original BIOSes are already in use in nds-bootstrap (except for DSiWarehax).

**Comment by jvhellraiser** [comment] 2018-10-16 00:43
thinking about could it be  that the AP code use is wrong i mean maybe not in Emulators but in Twilight menu itself this exact code is not working.

**Comment by piratesephiroth** [comment] 2018-10-16 04:06
It's a problem with nds-bootstrap, not with the code.
As I said, any AR  code that uses that are of memory to write instructions causes the game to crash when it tries to run it, becuase nds-bootstrap is putting stuff there already.
It happens with any game.

**Comment by ShadowOne333** [comment] 2018-12-05 20:17
Is this issue still present in the latest v0.12.3 (Rev 01) release?
I heard some changes were done to the reserved area mentioned previously (or something of the likes), so that got me thinking it Dark Dawn got fixed with one of those commits.

**Comment by RocketRobz** [comment] 2018-12-05 20:37
The issue is still present.

**Comment by leosonic256** [comment] 2019-01-02 05:57
Hi, Has anyone been able to solve this problem? I would love to play Golden Sun NDS on my 3DS.

**Comment by ahezard** [comment] 2019-01-19 00:12
The game is accessing the card via the dma method so the issue may be related to the not proper implementation of this method.

**Comment by ahezard** [comment] 2019-01-31 23:20
Duplicate #252

**Comment by ahezard** [comment] 2019-01-31 23:20
Closed as this is a duplicate

**Closed by ahezard** 2019-01-31 23:20 UTC

**Comment by Fau57** [comment] 2021-06-12 15:55
Hey guys this may seem silly but it's been two years ish since it was closed has anyone actually gotten golden sun dark dawn to work with TWiLight menu ++ or even some other way work around?

**Comment by RocketRobz** [comment] 2021-06-12 19:52
This issue is a duplicate.
This one is still open, as the issue isn't fixed: https://github.com/DS-Homebrew/nds-bootstrap/issues/252
