### ISSUE TITLE
Dragon Quest IX stuck after Character Creation.

### ISSUE THREAD

**Issue by SaulJoker** [ahezard/nds-bootstrap#230] opened 2018-06-22 20:16 UTC
After creating a character in a new save, the game gets stuck as soon as you finish creating your character. This issue already existed, but was apparently supposed to be fixed within the latest 3-4 releases. However, I just tested this in the latest version, and it appears to persist.

**Comment by Kalanyr** [comment] 2018-09-01 23:02
I can confirm that there certainly are issues with all enhancements turned on, which include random-ish hard freezes (eg when performing actions inside the church or when transitioning into buildings, I had this happen when I entered the inn. and when I exited after a successful entry).  

Character creation inside an existing save (ie for a new party member) works fine. 

(I used an existing save to test this, as I was going to see if creating a character at the Inn also froze.)

After deleting the save Dragon Quest IX freezes upon load , though a save file is created (this may be a consequence of me not using an AP patched rom).

I went back to the previous save and deleted the adventure log to test character creation on a new game.  I can confirm that the game does not freeze after creating a new character,  under these circumstances. 

Summary:  This issue does appear to be fixed now, but at least on an un-AP Patched ROM, this game still has significant issues.

**Comment by ahezard** [comment] 2019-03-03 16:03
So is this an AP issue or not? Please test with an AP patched rom

**Comment by ahezard** [comment] 2019-03-03 17:33
I was not able to reproduce the issue

**Comment by Kalanyr** [comment] 2019-03-03 17:39
Just tested on an AP patched rom on the latest official release. 

The OP's problem is fixed. 

All problems that I reported seem to be fixed as well.

**Comment by ahezard** [comment] 2019-03-03 17:42
Thanks for the feedback. So I close the issue

**Closed by ahezard** 2019-03-03 17:42 UTC
Labels: AP Issue, Bug, Cannot reproduce, Needs Testing, Retail

**Comment by Kobazco** [comment] 2019-05-11 21:48
Hi I still have these exact same issues despite it being said here that they have been fixed? Is it due to not having an AP patched rom? If so where can I find the AP finding it online has been impossible due to decade old dead rom links

**Comment by RocketRobz** [comment] 2019-05-12 06:43
Search for a tool called DS-Scene ROM Tool.
